"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['menubar.py']
DATA_FILES = ['static/img/icon/icon.png']
OPTIONS = {
    'iconfile': 'static/img/icon/icon.png'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
